workflows:
  signal-android-linux_x2:
    name: Signal Android Build on Linux_x2
    instance_type: linux_x2
    max_build_duration: 60  # minutes, adjust as needed
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        ANDROID_SDK_ROOT: /usr/lib/android-sdk
        ANDROID_HOME: /usr/lib/android-sdk
        api_level: 33
        build_tools_version: '33.0.0'
        jdk: openjdk17

    scripts:
      - name: Install Android SDK platforms & build tools
        script: |
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
          sdkmanager --licenses || true

      - name: Verify Java version
        script: java -version

      - name: Clean Gradle build
        script: ./gradlew clean

      - name: Run unit tests
        script: ./gradlew testDebugUnitTest #--stacktrace --info --debug

      - name: Build debug APK
        script: ./gradlew assembleDebug #--stacktrace --info --debug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/testDebugUnitTest/*.html
      - app/build/reports/tests/testDebugUnitTest/*.xml

  signal-android-linux_x4:
    name: Signal Android Build on Linux_x4
    instance_type: linux_x2
    max_build_duration: 60  # minutes, adjust as needed
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
        ANDROID_SDK_ROOT: /usr/lib/android-sdk
        ANDROID_HOME: /usr/lib/android-sdk
        api_level: 33
        build_tools_version: '33.0.0'
        jdk: openjdk17

    scripts:
      - name: Install Android SDK platforms & build tools
        script: |
          yes | sdkmanager "platforms;android-33" "build-tools;33.0.0" "platform-tools"
          sdkmanager --licenses || true

      - name: Verify Java version
        script: java -version

      - name: Clean Gradle build
        script: ./gradlew clean

      - name: Run unit tests
        script: ./gradlew testDebugUnitTest --stacktrace --info --debug

      - name: Build debug APK
        script: ./gradlew assembleDebug --stacktrace --info --debug

    artifacts:
      - app/build/outputs/apk/debug/*.apk
      - app/build/reports/tests/testDebugUnitTest/*.html
      - app/build/reports/tests/testDebugUnitTest/*.xml
